use serde::{Deserialize, Serialize};

/// Default Nostr relays used by the NWC service.
pub const DEFAULT_NWC_RELAYS: &[&str] = &[
  "wss://relay.damus.io",
  "wss://nostr-pub.wellorder.net",
];

/// Configuration for the NWC service
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct NwcConfig {
  /// A list of Nostr relay URLs for NWC connections. If None, default relays will be used.
  pub relay_urls: Option<Vec<String>>,
  /// The secret key used by the wallet node. If None, it will be generated by the SDK
  pub secret_key: Option<String>,
}

impl NwcConfig {
  /// Returns the list of Nostr relays to use for NWC.
  ///
  /// If not configured, falls back to [DEFAULT_NWC_RELAYS].
  pub fn relays(&self) -> Vec<String> {
    match &self.relay_urls {
      Some(relays) => relays.clone(),
      None => DEFAULT_NWC_RELAYS.iter().map(|s| s.to_string()).collect(),
    }
  }
}
