services:
  rt-sync:
    environment:
      SQLITE_DIR_PATH: /app/db
    build:
      context: https://github.com/breez/data-sync.git
    user: "0:0"
    restart: on-failure
    ports:
      - 8088:8080
      - 8089:8081
    volumes:
      - rt-sync-data:/app/db

  waterfalls:
    build: ./waterfalls-service
    environment:
      - RPC_USER_PASSWORD=regtest:regtest
    command: waterfalls --network elements-regtest --esplora-url http://esplora:4003/api --use-esplora --listen 0.0.0.0:3102 --add-cors
    ports:
      - 3102:3102

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3120:3120"
    volumes:
      - ./waterfalls-service/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - waterfalls
    restart: on-failure

  ssl-proxy:
    network_mode: "host"
    build: ./proxy

  swapproxy:
    build: ./swapproxy-service
    ports:
      - 8387:8387
    environment:
      - BACKEND_URL=http://boltz-backend-nginx:9001
      - WEBSOCKET_BACKEND_URL=ws://boltz-backend-nginx:9001/v2/ws
      - PORT=8387
      - SQLITE_DB_PATH=requests.db
      - POSTGRES_URL=postgresql://admin:pass@swapproxy-db:5432/postgres
      - DANGEROUS_NO_CA_CERT=YES
    depends_on:
      swapproxy-db:
        condition: service_healthy

  swapproxy-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname postgres --username admin"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s

volumes:
  bitcoin-data:
    name: boltz-bitcoind-data
    external: true
  mempool-data:
    name: mempool-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mempool
  mempool-db-data:
    name: mempool-db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mempool-db
  rt-sync-data:
    name: rt-sync-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/rt-sync

networks:
  default:
    name: boltz_default
    external: true
